### ISSUE TITLE
Errors trying to use cb-core, cb-org, cb-org-reveal layers

### ISSUE THREAD

**Issue by rodlogic** [chrisbarrett/spacemacs-layers#1]
I am a bit new to spacemacs (and emacs in general) and found your layers here a tremendous help to get me started. However, I am getting the following errors:

```
Error (use-package): org-agenda :config: Symbol's function definition is void: f-join
Error (use-package): org-work :init: Symbol's function definition is void: f-join
Error (use-package): ox-reveal :config: Symbol's function definition is void: f-dirname
```

Is there something missing in my .spacemacs?

**Comment by chrisbarrett** [comment]
Cool, glad to hear it helps!

I install `f` in the bootstrap in my `.spacemacs`. Make sure you're using that--run `make` in this repo to symlink it into your home folder. If you're using you're own `.spacemacs`, have a look at the packages I'm installing during bootstrap and install them manually, e.g. `M-x package-install f`.

Let me know if that's not working for you, it's always possible that it only works on my machine. :p

**Comment by ydewit** [comment]
Yes, I missed that the first time. So this is a non-issue at this point.

**Comment by chrisbarrett** [comment]
Since people are apparently trying to use my config (uh-oh!) I've factored the bootstrap stuff out. If you want to bring-your-own `.spacemacs` you just need to call the appropriate functions from that file in your own `.spacemacs`.
