### ISSUE TITLE
ditaa installation?

### ISSUE THREAD

**Issue by biocyberman** [chrisbarrett/spacemacs-layers#16]
Hi 
How do you install `ditaa` ? I use Ubuntu and I can install it via `apt-get`, but reading this: http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-ditaa.org.html makes me think that there is a `emacs` or even `spacemacs` way to do it. Since I see you have ditaa snippet and no other mentioning of ditaa, I wonder how you install it in a proper way.

Kind regards
Vang

**Comment by chrisbarrett** [comment]
Hey, if your package manager has installed it correctly and you can run it, I think that's all you can really ask for. :) I barely used it, but it's just a random jar that you run with `java` iiirc.

**Comment by biocyberman** [comment]
Thanks. I downloaded the jar file to the `private` and customize the package's jar-path variable to point it there. It's working fine. Thanks.
