### ISSUE TITLE
Agenda file ~/.notes is not in `org-mode'

### ISSUE THREAD

**Issue by ydewit** [chrisbarrett/spacemacs-layers#2]
I am now using a spacemacs' develop branch, your .spacemacs and your repo. Things are working better except for a few hiccups. For instance, this is what I get when I try to org-capture a new todo:
```
org-agenda-get-day-entries: Agenda file ~/.notes is not in `org-mode'
```

I see that the following in your cb-org layer:
```
  (setq org-default-notes-file (f-join org-directory "notes.org"))
```
So I am not sure why it is giving me this error. Could the org layer have cached the default one ```~/.notes``` before cb-org has a chance to set it?

**Comment by chrisbarrett** [comment]
`~/notes.org` must be getting added to `org-agenda-files`. 

Check the value of `org-default-notes-file`. It should be `~/org/notes.org`. Also check your `.spacemacs` or `~/.emacs.d/custom.el` files aren't setting `org-directory`, `org-agenda-files` or `org-default-notes-file`.

**Comment by rodlogic** [comment]
I forgot to mention that I get this error when creating a new TODO using org-capture (```SPC-a-o-c``` then ```t```).

I have no changes to .emacs.d, I am using the ```develop``` branch and you .spacemacs as-is. Here is a grep on ```org-default-notes-file``` in the ```emacs.d``` folder:
```
elpa/org-20151109/org:     (setq org-default-notes-file (concat org-directory "/notes.org"))
elpa/org-plus-contrib-20151109/org:     (setq org-default-notes-file (concat org-directory "/notes.org"))
elpa/org-plus-contrib-20151109/org.el:(defcustom org-default-notes-file (convert-standard-filename "~/.notes")

The same grep on ```.spacemacs-layers```:
```
cb-org/packages.el:  (setq org-default-notes-file (f-join org-directory "notes.org"))
```

And here the value of ```org-default-notes-file```:
```
org-default-notes-file is a variable defined in `org.el'.
Its value is "/Users/rodlogic/org/notes.org"
Original value was "~/.notes"
```

So it is a bit strange that it's value is set to ```~/org/notes.org```, but the error still references ```~/.notes```.

If this works for you, I am wondering if I should just reinstall spacemacs from scratch and see what happens.

**Comment by chrisbarrett** [comment]
It's working for me. What is the value of `org-agenda-files` for you? If `~/notes` is in there, you can hack around the issue for now with:

```elisp
(setq org-agenda-files (delete "~/notes" org-agenda-files))
```

**Comment by rodlogic** [comment]
@chrisbarrett ok, finally found the problem. ```cb-agda``` layer was throwing an error due to package agda-mode not being found and that was probably screwing spacemacs configuration somehow (I would expect spacemacs to catch those to try and safely load the rest of the layers). As soon as I commented out that layer, everything seems to be working fine.

Thanks for the help and you can close this ticket.

**Comment by chrisbarrett** [comment]
Aaaah oh yep. You can fix that by pulling all the submodules. Glad you're sorted. :)
