### ISSUE TITLE
cb-org sets org-directory to ~/org while ~/Dropbox/org is present

### ISSUE THREAD

**Issue by yanok** [chrisbarrett/spacemacs-layers#4]
Hi, first of all let me thank you for your excellent configuration! I don't know if you are interested in bug reporting for it (I guess it works for you already), but if you do I have found a couple of other problems.

Back to this issue, it seems like the order of initialization is messed up:
`org-directory` is set up from `cb-org/post-init-org` which is probably too late. It's used from `use-package org-agenda :config` which apparently happens before `cb-org/post-init-org`. Is there a particular reason why `org-directory` should be defined from `post-init-org`? Also, I've found that `use-package org-agenda` invocation is at the top level, I'm not an spacemacs guru but I would expect it to be inside `cb-org/init-org-agenda`, is this done by intention?

**Comment by yanok** [comment]
OK, it looks like putting `use-package org-agenda` inside `cb-org/init-org-agenda` fixes this issue.

**Comment by chrisbarrett** [comment]
Thanks for the report. :) I've moved the initialisation for `org-directory` to the toplevel to resolve this. As for the structure of this layer, I haven't put the time in to port it to the layers system, so I just did the bare minimum to get it working.
