### ISSUE TITLE
fasd conflict with  cb-sunrise-commander

### ISSUE THREAD

**Issue by zwb-ict** [chrisbarrett/spacemacs-layers#6]
I use cb-sunrise-commander layer, when I run C-x d, I get error: 
```
fasd-add-file-to-db: Wrong type argument: stringp, nil
```

I have to close global-fasd-mode before I entered sunrise-commander. Is there a better way to resolve this conflict? Thank you!

**Comment by chrisbarrett** [comment]
I don't use fasd, so I dunno. ¯\_(ツ)_/¯

**Comment by zwb-ict** [comment]
@chrisbarrett  Thank you all the same. It'a fasd's bug. The fasd's author has solved this problem.
