### ISSUE TITLE
smart-ops-mode broke cc #include header complete

### ISSUE THREAD

**Issue by zwb-ict** [chrisbarrett/spacemacs-layers#8]
I use irony to complete c/c++ code,
with smart-ops-mode on, the input is:
```
#include < iostream >
```
not 
```
#include <iostream>
```

It brokes irony-header, and cause compile error.

**Comment by chrisbarrett** [comment]
I use yasnippet to insert includes so I never have the issue myself. On a blank line, typing `in` and pressing `<tab>` will pop up a list of import snippets.

**Comment by zwb-ict** [comment]
@chrisbarrett 
In dir
spacemacs-layers/cb-yasnippet/snippets/c-mode and c++mode
I didn't find ```include```, need myself to add it?

**Comment by chrisbarrett** [comment]
Heh, those snippets weren't under version control (they start with `#`). Fixed. ;)

**Comment by zwb-ict** [comment]
@chrisbarrett Cool! It's perfect now! Thank you for your help. Have a nice day!
